var gvjs_fQ="#990000",gvjs_gQ="annotationText",gvjs_hQ="certainty";gvjs_fL.prototype.Jm=gvjs_V(70,function(a,b){if(this.Xg===gvjs_cw)return this.av(a,b);throw Error(gvjs_2r);});gvjs_gL.prototype.Jm=gvjs_V(69,function(a,b){return this.av(a,b)});function gvjs_iQ(a){var b=new gvjs_LE;b.sa=function(){return a};return b}function gvjs_jQ(a){gvjs_fL.call(this,a);this.cc(gvjs_d,gvjs_8s,gvjs_S)}gvjs_o(gvjs_jQ,gvjs_fL);function gvjs_kQ(a){gvjs_fL.call(this,a);this.cc(gvjs_d,gvjs_1w,gvjs_S)}gvjs_o(gvjs_kQ,gvjs_fL);
function gvjs_lQ(a){gvjs_fL.call(this,a);this.cc(gvjs_d,gvjs_f,gvjs_S,"sparkline")}gvjs_o(gvjs_lQ,gvjs_fL);function gvjs_mQ(a){gvjs_fL.call(this,a);this.cc(gvjs_d,gvjs_e,gvjs_S)}gvjs_o(gvjs_mQ,gvjs_fL);function gvjs_nQ(a){gvjs_fL.call(this,a);this.cc(gvjs_Ed)}gvjs_o(gvjs_nQ,gvjs_fL);gvjs_nQ.prototype.Jm=function(a,b){return this.av(a,b)};function gvjs_oQ(a){gvjs_fL.call(this,a);this.cc(gvjs_vt)}gvjs_o(gvjs_oQ,gvjs_fL);function gvjs_pQ(a){gvjs_fL.call(this,a);this.cc(gvjs_d,gvjs_it,gvjs_U)}
gvjs_o(gvjs_pQ,gvjs_fL);gvjs_pQ.prototype.Jm=function(a,b){return this.av(a,b)};function gvjs_qQ(a){gvjs_fL.call(this,a);this.cc(gvjs_d,gvjs_Ct,gvjs_S)}gvjs_o(gvjs_qQ,gvjs_fL);function gvjs_rQ(a){gvjs_fL.call(this,a);this.cc(gvjs_d,gvjs_it,gvjs_S)}gvjs_o(gvjs_rQ,gvjs_fL);gvjs_rQ.prototype.Jm=function(a,b){return this.av(a,b)};function gvjs_sQ(a){gvjs_fL.call(this,a);this.cc(gvjs_1u,gvjs_it,gvjs_S)}gvjs_o(gvjs_sQ,gvjs_fL);gvjs_q(gvjs_gc,gvjs_fL,void 0);gvjs_fL.prototype.draw=gvjs_fL.prototype.draw;
gvjs_fL.prototype.clearChart=gvjs_fL.prototype.Jb;gvjs_fL.prototype.getImageURI=gvjs_fL.prototype.ah;gvjs_fL.prototype.getSelection=gvjs_fL.prototype.getSelection;gvjs_fL.prototype.setSelection=gvjs_fL.prototype.setSelection;gvjs_fL.prototype.dump=gvjs_fL.prototype.dump;gvjs_fL.prototype.getChartLayoutInterface=gvjs_fL.prototype.Ql;gvjs_fL.prototype.getContainer=gvjs_fL.prototype.getContainer;gvjs_fL.prototype.setAction=gvjs_fL.prototype.xh;gvjs_fL.prototype.getAction=gvjs_fL.prototype.ng;
gvjs_fL.prototype.removeAction=gvjs_fL.prototype.th;gvjs_q(gvjs_5b,gvjs_jQ,void 0);gvjs_jQ.prototype.draw=gvjs_jQ.prototype.draw;gvjs_jQ.prototype.clearChart=gvjs_jQ.prototype.Jb;gvjs_jQ.prototype.getImageURI=gvjs_jQ.prototype.ah;gvjs_jQ.prototype.getSelection=gvjs_jQ.prototype.getSelection;gvjs_jQ.prototype.setSelection=gvjs_jQ.prototype.setSelection;gvjs_jQ.prototype.setAction=gvjs_jQ.prototype.xh;gvjs_jQ.prototype.getAction=gvjs_jQ.prototype.ng;gvjs_jQ.prototype.removeAction=gvjs_jQ.prototype.th;
gvjs_q(gvjs_6b,gvjs_pQ,void 0);gvjs_pQ.prototype.computeDiff=gvjs_pQ.prototype.Jm;gvjs_pQ.prototype.draw=gvjs_pQ.prototype.draw;gvjs_pQ.prototype.clearChart=gvjs_pQ.prototype.Jb;gvjs_pQ.prototype.getImageURI=gvjs_pQ.prototype.ah;gvjs_pQ.prototype.getSelection=gvjs_pQ.prototype.getSelection;gvjs_pQ.prototype.setSelection=gvjs_pQ.prototype.setSelection;gvjs_pQ.prototype.setAction=gvjs_pQ.prototype.xh;gvjs_pQ.prototype.getAction=gvjs_pQ.prototype.ng;gvjs_pQ.prototype.removeAction=gvjs_pQ.prototype.th;
gvjs_q(gvjs_7b,gvjs_oQ,void 0);gvjs_oQ.prototype.draw=gvjs_oQ.prototype.draw;gvjs_oQ.prototype.clearChart=gvjs_oQ.prototype.Jb;gvjs_oQ.prototype.getImageURI=gvjs_oQ.prototype.ah;gvjs_oQ.prototype.getSelection=gvjs_oQ.prototype.getSelection;gvjs_oQ.prototype.setSelection=gvjs_oQ.prototype.setSelection;gvjs_oQ.prototype.setAction=gvjs_oQ.prototype.xh;gvjs_oQ.prototype.getAction=gvjs_oQ.prototype.ng;gvjs_oQ.prototype.removeAction=gvjs_oQ.prototype.th;gvjs_q(gvjs_9b,gvjs_qQ,void 0);
gvjs_qQ.prototype.draw=gvjs_qQ.prototype.draw;gvjs_qQ.prototype.clearChart=gvjs_qQ.prototype.Jb;gvjs_qQ.prototype.getImageURI=gvjs_qQ.prototype.ah;gvjs_qQ.prototype.getSelection=gvjs_qQ.prototype.getSelection;gvjs_qQ.prototype.setSelection=gvjs_qQ.prototype.setSelection;gvjs_qQ.prototype.setAction=gvjs_qQ.prototype.xh;gvjs_qQ.prototype.getAction=gvjs_qQ.prototype.ng;gvjs_qQ.prototype.removeAction=gvjs_qQ.prototype.th;gvjs_q(gvjs_sc,gvjs_sQ,void 0);gvjs_sQ.prototype.draw=gvjs_sQ.prototype.draw;
gvjs_sQ.prototype.clearChart=gvjs_sQ.prototype.Jb;gvjs_sQ.prototype.getImageURI=gvjs_sQ.prototype.ah;gvjs_sQ.prototype.getSelection=gvjs_sQ.prototype.getSelection;gvjs_sQ.prototype.setSelection=gvjs_sQ.prototype.setSelection;gvjs_sQ.prototype.setAction=gvjs_sQ.prototype.xh;gvjs_sQ.prototype.getAction=gvjs_sQ.prototype.ng;gvjs_sQ.prototype.removeAction=gvjs_sQ.prototype.th;gvjs_q(gvjs_dc,gvjs_rQ,void 0);gvjs_rQ.prototype.computeDiff=gvjs_rQ.prototype.Jm;gvjs_rQ.prototype.draw=gvjs_rQ.prototype.draw;
gvjs_rQ.prototype.clearChart=gvjs_rQ.prototype.Jb;gvjs_rQ.prototype.getImageURI=gvjs_rQ.prototype.ah;gvjs_rQ.prototype.getSelection=gvjs_rQ.prototype.getSelection;gvjs_rQ.prototype.setSelection=gvjs_rQ.prototype.setSelection;gvjs_rQ.prototype.setAction=gvjs_rQ.prototype.xh;gvjs_rQ.prototype.getAction=gvjs_rQ.prototype.ng;gvjs_rQ.prototype.removeAction=gvjs_rQ.prototype.th;gvjs_q(gvjs_fc,gvjs_oL,void 0);gvjs_oL.prototype.draw=gvjs_oL.prototype.draw;gvjs_oL.prototype.clearChart=gvjs_oL.prototype.Jb;
gvjs_oL.prototype.getImageURI=gvjs_oL.prototype.ah;gvjs_oL.prototype.getSelection=gvjs_oL.prototype.getSelection;gvjs_oL.prototype.setSelection=gvjs_oL.prototype.setSelection;gvjs_oL.prototype.setAction=gvjs_oL.prototype.xh;gvjs_oL.prototype.getAction=gvjs_oL.prototype.ng;gvjs_oL.prototype.removeAction=gvjs_oL.prototype.th;gvjs_q(gvjs_Ac,gvjs_mQ,void 0);gvjs_mQ.prototype.draw=gvjs_mQ.prototype.draw;gvjs_mQ.prototype.clearChart=gvjs_mQ.prototype.Jb;gvjs_mQ.prototype.getImageURI=gvjs_mQ.prototype.ah;
gvjs_mQ.prototype.getSelection=gvjs_mQ.prototype.getSelection;gvjs_mQ.prototype.setSelection=gvjs_mQ.prototype.setSelection;gvjs_mQ.prototype.setAction=gvjs_mQ.prototype.xh;gvjs_mQ.prototype.getAction=gvjs_mQ.prototype.ng;gvjs_mQ.prototype.removeAction=gvjs_mQ.prototype.th;gvjs_q(gvjs_Kc,gvjs_gL,void 0);gvjs_gL.prototype.computeDiff=gvjs_gL.prototype.Jm;gvjs_gL.prototype.draw=gvjs_gL.prototype.draw;gvjs_gL.prototype.clearChart=gvjs_gL.prototype.Jb;gvjs_gL.prototype.getImageURI=gvjs_gL.prototype.ah;
gvjs_gL.prototype.getSelection=gvjs_gL.prototype.getSelection;gvjs_gL.prototype.setSelection=gvjs_gL.prototype.setSelection;gvjs_gL.prototype.setAction=gvjs_gL.prototype.xh;gvjs_gL.prototype.getAction=gvjs_gL.prototype.ng;gvjs_gL.prototype.removeAction=gvjs_gL.prototype.th;gvjs_q(gvjs_Oc,gvjs_nQ,void 0);gvjs_nQ.prototype.computeDiff=gvjs_nQ.prototype.Jm;gvjs_nQ.prototype.draw=gvjs_nQ.prototype.draw;gvjs_nQ.prototype.clearChart=gvjs_nQ.prototype.Jb;gvjs_nQ.prototype.getImageURI=gvjs_nQ.prototype.ah;
gvjs_nQ.prototype.getSelection=gvjs_nQ.prototype.getSelection;gvjs_nQ.prototype.setSelection=gvjs_nQ.prototype.setSelection;gvjs_nQ.prototype.setAction=gvjs_nQ.prototype.xh;gvjs_nQ.prototype.getAction=gvjs_nQ.prototype.ng;gvjs_nQ.prototype.removeAction=gvjs_nQ.prototype.th;gvjs_q(gvjs_Qc,gvjs_lQ,void 0);gvjs_lQ.prototype.draw=gvjs_lQ.prototype.draw;gvjs_lQ.prototype.clearChart=gvjs_lQ.prototype.Jb;gvjs_lQ.prototype.getImageURI=gvjs_lQ.prototype.ah;gvjs_lQ.prototype.getSelection=gvjs_lQ.prototype.getSelection;
gvjs_lQ.prototype.setSelection=gvjs_lQ.prototype.setSelection;gvjs_lQ.prototype.setAction=gvjs_lQ.prototype.xh;gvjs_lQ.prototype.getAction=gvjs_lQ.prototype.ng;gvjs_lQ.prototype.removeAction=gvjs_lQ.prototype.th;gvjs_q(gvjs_Rc,gvjs_kQ,void 0);gvjs_kQ.prototype.draw=gvjs_kQ.prototype.draw;gvjs_kQ.prototype.clearChart=gvjs_kQ.prototype.Jb;gvjs_kQ.prototype.getImageURI=gvjs_kQ.prototype.ah;gvjs_kQ.prototype.getSelection=gvjs_kQ.prototype.getSelection;gvjs_kQ.prototype.setSelection=gvjs_kQ.prototype.setSelection;
gvjs_kQ.prototype.setAction=gvjs_kQ.prototype.xh;gvjs_kQ.prototype.getAction=gvjs_kQ.prototype.ng;gvjs_kQ.prototype.removeAction=gvjs_kQ.prototype.th;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
function gvjs_tQ(a,b,c,d){gvjs_nC.call(this,a,b,c,null,d)}gvjs_t(gvjs_tQ,gvjs_nC);gvjs_tQ.prototype.rg=function(){do gvjs_tQ.G.next.call(this);while(-1==this.tj);return this.node};gvjs_tQ.prototype.next=gvjs_tQ.prototype.rg;gvjs_eh(gvjs_b);function gvjs_uQ(a){return(new gvjs_um).cd().sanitize(a)};
