import"../../chunk-T4RFKMZH.js";import{a as P}from"../../chunk-ZZTYZOVH.js";import"../../chunk-EGRHWZRV.js";import{a as S,b as u,f as U}from"../../chunk-6CNPBMSA.js";import{a as k,d as E,i as v}from"../../chunk-IZOY2GXC.js";import{a as y}from"../../chunk-AEEBJP5X.js";import"../../chunk-4IBQV6BB.js";import"../../chunk-2QPOFOOR.js";import{a as T,b as m}from"../../chunk-2DNXUWM5.js";import{b as h}from"../../chunk-EDKSZH7L.js";function B(g){return g.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}var f=class{windowOpenExtended(l,e,n,t,a){let o={width:e,height:n,scrollbars:0,target:t??"_blank"};if(a)for(let w in a)P.hasProperty(a,w)&&(o[w]=a[w]);let c=window.screen,d=window.screenLeft??0,r=window.screenTop??0,i,p;return window.innerWidth?i=window.innerWidth:document.documentElement.clientWidth?i=document.documentElement.clientWidth:i=c.width,window.innerHeight?p=window.innerHeight:document.documentElement.clientHeight?p=document.documentElement.clientHeight:p=c.height,o.left=i/2-e/2+d,o.top=p/2-n/2+r,this.openWindow(l,o)}openWindow(l,e,n){e=e||{};let t=n??window,a=l,o=e.target,c=[];for(let i in e)switch(i){case"width":case"height":case"top":case"left":c.push(i+"="+e[i]?.toString());break;case"target":case"noreferrer":break;default:c.push(i+"="+(e[i]?1:0))}let d=c.join(","),r;return e.noreferrer?(r=t.open("",o,d),r&&(r.opener=null,a=B(a),r.document.write('<META HTTP-EQUIV="refresh" content="0; url='+a+'">'),r.document.close())):r=t.open(a,o,d),r}},b=new f;var x=k`
  :host {
    display: flex;
    align-items: center;
    position: relative;
    box-sizing: border-box;
    font-size: 0;
    line-height: 0;
  }

  @media (min-width: ${768}px) {
    :host(:hover) ::slotted(ui-social-share) {
      background-color: var(--cp-grey-light-6);
    }

    ::slotted(ui-social-share[type='whatsapp']) {
      display: none;
    }
  }
`;var s=class extends v{constructor(){super(...arguments);this.brandname="";this.headline="";this.url="";this.baseUrls={facebookSharer:"https://www.facebook.com/sharer/sharer.php",facebookBase:"https://www.facebook.com/login.php",twitter:"https://x.com/intent/tweet",whatsapp:"whatsapp://send"}}get componentPath(){return this.getAttribute("data-component-path")??""}render(){return E`
      <slot @slotchange="${this.handleSlotChange}"></slot>
    `}handleSlotChange(){this.socialShareButtons.forEach(e=>{e.addEventListener("customEventSocialClick",n=>{if(m.publish("video:pauseAllPlayers"),m.publish("globalReco:userFeedback","socialShareCount"),n.detail){let t=n.detail;switch(t.type){case"facebook":this.shareViaFacebook();break;case"twitter":this.shareViaTwitter(t.account??"",t.via);break;case"mail":this.shareViaMail();break;case"whatsapp":this.shareViaWhatsapp();break;case"share":this.shareViaNativeShare();break;default:break}}})})}sendBrainTrackingEvent(e){m.publish("social:share",{referrer:"&referrer=undefined",click1:"&click1=undefined",click2:"&click2=undefined",click3:"&click3=undefined",click4:"&click4=undefined",type:"&type=hidden",clickname:"&clickname="+e})}sendTrackingEvent(e){y.callTealiumLink({businessEventType:"userAction",componentPath:`${this.componentPath}.${e}`,componentName:`share-icon.${e}`,elementTagName:"button",eventType:"mousedown"})}shareViaWhatsapp(){this.sendBrainTrackingEvent("whatsapp"),this.sendTrackingEvent("whatsapp");let e=new URL(this.baseUrls.whatsapp);e.searchParams.append("text",`Hallo,

ich habe gerade diesen interessanten Beitrag bei ${this.brandname}
       gefunden: ${this.headline} - ${this.url}#.wa.whatsapp`),window.location.href=e.toString()}shareViaMail(){let e="%0D%0A",n=encodeURIComponent("Leseempfehlung: "+this.headline),t="Hallo%2C%0A%0Aich%20habe%20gerade%20diesen%20interessanten%20Beitrag%20bei%20"+encodeURIComponent(this.brandname+" gefunden:")+e;t+=encodeURIComponent(this.headline)+e,t+=encodeURIComponent(this.url+"#.wa.mailsent")+e+e,t+=encodeURIComponent("Weitere aktuelle News bei "+this.brandname+" "+window.ui.pageinfo.home),this.sendBrainTrackingEvent("sendmail"),this.sendTrackingEvent("mail");let a="mailto:?subject=";a+=n,a+="&body=",a+=t,window.location.href=a}shareViaFacebook(){this.sendBrainTrackingEvent("facebook_recommend"),this.sendTrackingEvent("facebook");let e=this.url.replace(/(\/\/dev\.)|(\/\/test\.)|(\/\/pre\.)|(\/\/local\.)|(\/\/red\.)|(\/\/pattern-lab\.dev\.)/gi,"//"),n=new URL(this.baseUrls.facebookSharer);n.searchParams.append("u",e+"#.wa.facebook"),n.searchParams.append("t",this.headline+" | "+this.brandname),n.searchParams.append("rel","login"),n.searchParams.append("display","popup");let t=`${this.baseUrls.facebookBase}?next=${n.toString()}`;b.windowOpenExtended(t,675,375)}shareViaTwitter(e,n){if(n){this.sendBrainTrackingEvent("tweet"),this.sendTrackingEvent("twitter");let t=new URL(this.baseUrls.twitter);t.searchParams.append("url",this.url+"#.wa.twitter"),e?(t.searchParams.append("via",e),t.searchParams.append("text",this.headline)):t.searchParams.append("text",this.headline+n),b.windowOpenExtended(t.toString(),550,460)}}async shareViaNativeShare(){this.sendBrainTrackingEvent("share_open"),this.sendTrackingEvent("native-share");try{await navigator.share({title:document.title,url:this.url}),this.sendBrainTrackingEvent("share_success")}catch(e){T.logUnknownError(e,"Social"),this.sendBrainTrackingEvent("share_error")}}};s.styles=[x],h([u()],s.prototype,"brandname",2),h([u()],s.prototype,"headline",2),h([u()],s.prototype,"url",2),h([U({selector:"ui-social-share",flatten:!1})],s.prototype,"socialShareButtons",2),s=h([S("ui-social")],s);export{s as Social};
//# sourceMappingURL=social.js.map
